
package br.com.prmarinho.service.store.client;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Service", targetNamespace = "http://resource.webservice.correios.com.br/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Service {


    /**
     * 
     * @param senha
     * @param tipo
     * @param resultado
     * @param lingua
     * @param usuario
     * @param objetos
     * @return
     *     returns br.com.prmarinho.service.store.client.Sroxml
     */
    @WebMethod(action = "buscaEventos")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "buscaEventos", targetNamespace = "http://resource.webservice.correios.com.br/", className = "br.com.prmarinho.service.store.client.BuscaEventos")
    @ResponseWrapper(localName = "buscaEventosResponse", targetNamespace = "http://resource.webservice.correios.com.br/", className = "br.com.prmarinho.service.store.client.BuscaEventosResponse")
    @Action(input = "buscaEventos", output = "http://resource.webservice.correios.com.br/Service/buscaEventosResponse")
    public Sroxml buscaEventos(
        @WebParam(name = "usuario", targetNamespace = "")
        String usuario,
        @WebParam(name = "senha", targetNamespace = "")
        String senha,
        @WebParam(name = "tipo", targetNamespace = "")
        String tipo,
        @WebParam(name = "resultado", targetNamespace = "")
        String resultado,
        @WebParam(name = "lingua", targetNamespace = "")
        String lingua,
        @WebParam(name = "objetos", targetNamespace = "")
        String objetos);

    /**
     * 
     * @param senha
     * @param tipo
     * @param resultado
     * @param lingua
     * @param usuario
     * @param objetos
     * @return
     *     returns br.com.prmarinho.service.store.client.Sroxml
     */
    @WebMethod(action = "buscaEventosLista")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "buscaEventosLista", targetNamespace = "http://resource.webservice.correios.com.br/", className = "br.com.prmarinho.service.store.client.BuscaEventosLista")
    @ResponseWrapper(localName = "buscaEventosListaResponse", targetNamespace = "http://resource.webservice.correios.com.br/", className = "br.com.prmarinho.service.store.client.BuscaEventosListaResponse")
    @Action(input = "buscaEventosLista", output = "http://resource.webservice.correios.com.br/Service/buscaEventosListaResponse")
    public Sroxml buscaEventosLista(
        @WebParam(name = "usuario", targetNamespace = "")
        String usuario,
        @WebParam(name = "senha", targetNamespace = "")
        String senha,
        @WebParam(name = "tipo", targetNamespace = "")
        String tipo,
        @WebParam(name = "resultado", targetNamespace = "")
        String resultado,
        @WebParam(name = "lingua", targetNamespace = "")
        String lingua,
        @WebParam(name = "objetos", targetNamespace = "")
        List<String> objetos);

}
